// Broad term groups, not a scheme-specific teaching sequence. See README.md.
// Each word has its own locally hosted picture. Use British English spellings.
// Each later term adds new patterns and revisits all earlier words.
// Nouns are chosen for clear picture matching; avoid obscure vocabulary as padding.
export const NEW_WORDS = {
  autumn: [
    "cat",
    "dog",
    "pig",
    "hen",
    "rat",
    "fox",
    "bat",
    "ant",
    "bee",
    "duck",
    "fish",
    "sheep",
    "goat",
    "cow",
    "owl",
    "snail",
    "frog",
    "crab",
    "shrimp",
    "sun",
    "moon",
    "star",
    "rain",
    "cloud",
    "hat",
    "cap",
    "socks",
    "boot",
    "bed",
    "cup",
    "map",
    "bell",
    "bus",
    "car",
    "ship",
    "boat",
    "train",
    "tram",
    "egg",
    "nut",
    "chips",
    "corn",
    "milk",
    "bag",
    "pen",
    "pin",
    "web",
    "log",
    "lock",
    "rock",
    "box",
    "book",
    "hook",
    "ring",
    "chick",
    "shell",
    "shark",
    "tooth",
    "chain",
    "chair",
    "coin",
    "ear",
    "tree",
    "drum",
    "flag",
    "tent",
    "nest",
    "gift",
    "plug",
    "truck",
    "hand",
    "leg",
    "foot",
    "brush",
    "spoon",
    "coat",
    "soap",
    "torch",
    "scarf",
    "crown",
    "clock",
  ],
  spring: [
    "cake",
    "bike",
    "kite",
    "bone",
    "phone",
    "rose",
    "snake",
    "whale",
    "peach",
    "leaf",
    "key",
    "wheel",
    "snow",
    "pie",
    "tie",
    "fly",
    "eye",
    "nose",
    "hole",
    "tube",
    "seal",
    "beans",
    "meat",
    "spider",
    "tiger",
    "lion",
    "zebra",
    "donkey",
    "monkey",
    "purse",
    "bird",
    "shirt",
    "girl",
    "worm",
    "saw",
    "ball",
    "wave",
    "slide",
    "skate",
    "plate",
    "grapes",
  ],
  summer: [
    "bread",
    "feather",
    "pear",
    "bear",
    "deer",
    "horse",
    "mouse",
    "house",
    "cheese",
    "rabbit",
    "carrot",
    "rocket",
    "apple",
    "lemon",
    "melon",
    "pepper",
    "cherries",
    "banana",
    "tomato",
    "potato",
    "mushroom",
    "pumpkin",
    "ribbon",
    "basket",
    "bucket",
    "magnet",
    "ladder",
    "hammer",
    "ticket",
    "helmet",
    "trumpet",
    "penguin",
    "parrot",
    "otter",
    "badger",
    "hamster",
    "beaver",
    "lizard",
    "camel",
    "cricket",
    "lobster",
    "elephant",
    "dolphin",
    "octopus",
    "hippo",
    "hedgehog",
    "butterfly",
    "dragon",
    "snowman",
    "sunflower",
    "teapot",
    "toothbrush",
    "jellyfish",
    "sandwich",
    "rainbow",
    "sunglasses",
    "window",
    "mirror",
    "tractor",
    "robot",
    "crayon",
    "pencil",
    "teddy",
    "swan",
    "watch",
    "shoe",
    "dice",
  ],
};

const groups = {
  "year1-autumn": NEW_WORDS.autumn,
  "year1-spring": [...NEW_WORDS.autumn, ...NEW_WORDS.spring],
  "year1-summer": [
    ...NEW_WORDS.autumn,
    ...NEW_WORDS.spring,
    ...NEW_WORDS.summer,
  ],
};

// Prevent related pictures from being shown together when either could fit a word.
const relatedPictures = [
  ["hat", "cap", "helmet"],
  ["boat", "ship"],
  ["cup", "teapot"],
  ["boot", "shoe", "skate"],
  ["bear", "teddy"],
  ["hen", "chick"],
  ["brush", "pen", "pencil", "crayon"],
  ["chair", "plate"],
  ["sun", "sunflower"],
  ["snow", "snowman"],
  ["tooth", "toothbrush"],
  ["fish", "shark", "jellyfish"],
  ["rain", "cloud", "snow"],
  ["moon", "star"],
  ["hand", "leg", "foot"],
  ["bag", "basket"],
];

export const YEARS = [{ id: "year1", name: "Year 1", ages: "Ages 5–6" }];

export const TERMS = [
  {
    id: "autumn",
    name: "Autumn",
    image: "autumn",
    note: "A fresh beginning",
    colour: "peach",
  },
  {
    id: "spring",
    name: "Spring",
    image: "spring",
    note: "Growing in confidence",
    colour: "pink",
  },
  {
    id: "summer",
    name: "Summer",
    image: "sun",
    note: "Look how far you’ve come!",
    colour: "yellow",
  },
];

export const LEVELS = {
  "year1-autumn": {
    title: "Building on our sounds",
    description: "Revisit sounds and blend with confidence",
    focus: "ou · oi · air · ow · ar · ear",
  },
  "year1-spring": {
    title: "New ways to make sounds",
    description: "Alternative spellings and split digraphs",
    focus: "a–e · i–e · o–e · ea · ey · wh",
  },
  "year1-summer": {
    title: "Brilliant word explorers",
    description: "More spellings and longer words",
    focus: "ea · ear · eer · ou · two syllables",
  },
};

export const WORD_BANKS = Object.fromEntries(
  Object.entries(groups).map(([id, words]) => [
    id,
    words.map((word) => ({
      id: word,
      word,
      image: `./assets/pictures/${word}.png`,
      stage: NEW_WORDS.autumn.includes(word)
        ? 0
        : NEW_WORDS.spring.includes(word)
          ? 1
          : 2,
      related: relatedPictures.filter((group) => group.includes(word)).flat(),
    })),
  ]),
);

export function getBank(year, term) {
  const bank = WORD_BANKS[`${year}-${term}`];
  if (!bank) throw new Error("Please choose a valid school year and term.");
  return bank;
}
